name: tastyworks-unofficial # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.16' # just for humans, typically '1.2+git' or '1.3.2'
summary:  TastyWorks platform packaged as a snap for compatibility # 79 char long summary
description: |
  UNOFFICIAL snap package of TastyWorks trading platform.

grade: stable
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  tastyworks:
    command: desktop-launch $SNAP/opt/tastyworks/bin/tastyworks
    desktop: opt/tastyworks/bin/tastyworks.desktop
    environment:
      DISABLE_WAYLAND: 1
      JAVA_TOOL_OPTIONS: "-Duser.home=$SNAP_USER_COMMON"
    plugs:
      - network
      - opengl
      - x11
#      - dbus
#      - alsa
#      - pulseaudio
#      - audio-playback
      - desktop
      - desktop-legacy
      - home
#      - javafx-cache
#      - tastyworks-conf
      - gsettings
      - mount-observe
      - network-observe
      - network-bind

parts:
  tasty-deb:
    source: https://download.tastyworks.com/desktop-1.x.x/1.0.16/tastyworks-1.0.16-1_amd64.deb
#deb/tastyworks-1.0.16-1_amd64.deb 
#https://download.tastyworks.com/desktop-1.x.x/1.0.16/tastyworks-1.0.16-1_amd64.deb
    source-type: deb
    plugin: dump
    stage-packages:
      - libfreetype6
      - libpng16-16
      - libx11-6
      - libgl1
      - libxtst6
      - openjfx
# sound doesn't work anyway
#      - libasound2
#      - libcanberra-gtk-module
#      - libcanberra-gtk3-module
#      - libgstreamer1.0-0
#      - gstreamer1.0-pulseaudio
#      - gstreamer1.0-x
    override-build: |
      snapcraftctl build
      #fix icon path
      sed -i 's|Icon=.*$|Icon=${SNAP}/opt/tastyworks/bin/tastyworks.png|g' $SNAPCRAFT_PART_INSTALL/opt/tastyworks/bin/tastyworks.desktop
    after: [desktop-gtk3]
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git 
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5

# these below are not used and not needed
plugs:
  javafx-cache:
    interface: personal-files
    read:
      - $HOME/.openjfx/cache
    write:
      - $HOME/.openjfx/cache

  tastyworks-conf:
    interface: personal-files
    read:
      - $HOME/.tastyworks
#      - $HOME/.tastyworks/desktop/latest-manifest.json
    write:
      - $HOME/.tastyworks
#      - $HOME/.tastyworks/desktop/tastyworks.log

